"""your_migration_name

Revision ID: 85206779face
Revises: fa3e3a5ee5d9
Create Date: 2025-08-12 15:12:12.372692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85206779face'
down_revision: Union[str, Sequence[str], None] = 'fa3e3a5ee5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_proposals_id'), table_name='business_proposals')
    op.drop_table('business_proposals')
    op.drop_index(op.f('ix_partnership_agreements_id'), table_name='partnership_agreements')
    op.drop_table('partnership_agreements')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_short_videos_id'), table_name='short_videos')
    op.drop_table('short_videos')
    op.drop_index(op.f('ix_terms_of_service_id'), table_name='terms_of_service')
    op.drop_table('terms_of_service')
    op.drop_index(op.f('ix_ndas_id'), table_name='ndas')
    op.drop_table('ndas')
    op.drop_index(op.f('ix_logos_id'), table_name='logos')
    op.drop_table('logos')
    op.drop_index(op.f('ix_privacy_policies_id'), table_name='privacy_policies')
    op.drop_table('privacy_policies')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'image')
    op.drop_column('users', 'name')
    op.create_table('privacy_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('docs_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('privacy_policies_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('privacy_policies_pkey'))
    )
    op.create_index(op.f('ix_privacy_policies_id'), 'privacy_policies', ['id'], unique=False)
    op.create_table('logos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logo_image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('remove_bg_logo_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('logo_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('logo_vision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_palette_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_style', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('logos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('logos_pkey'))
    )
    op.create_index(op.f('ix_logos_id'), 'logos', ['id'], unique=False)
    op.create_table('ndas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disclosing_party', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receiving_party', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('docs_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ndas_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ndas_pkey'))
    )
    op.create_index(op.f('ix_ndas_id'), 'ndas', ['id'], unique=False)
    op.create_table('terms_of_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('docs_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('terms_of_service_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('terms_of_service_pkey'))
    )
    op.create_index(op.f('ix_terms_of_service_id'), 'terms_of_service', ['id'], unique=False)
    op.create_table('short_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('aspect_ratio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('audio_generation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('watermark', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('person_generation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('short_videos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('short_videos_pkey'))
    )
    op.create_index(op.f('ix_short_videos_id'), 'short_videos', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('party1_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('party2_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('docs_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('contracts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contracts_pkey'))
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('partnership_agreements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('party1_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('party2_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partnership_purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('docs_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('partnership_agreements_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('partnership_agreements_pkey'))
    )
    op.create_index(op.f('ix_partnership_agreements_id'), 'partnership_agreements', ['id'], unique=False)
    op.create_table('business_proposals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('docs_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('business_proposals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_proposals_pkey'))
    )
    op.create_index(op.f('ix_business_proposals_id'), 'business_proposals', ['id'], unique=False)
    # ### end Alembic commands ###
