"""add fullname and other missing columns to users table

Revision ID: 97b376b85238
Revises: 7a309c116dc8
Create Date: 2025-08-12 21:53:53.602387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b376b85238'
down_revision: Union[str, Sequence[str], None] = '7a309c116dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing columns to users table
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True, server_default='email'))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    
    # Create unique constraint on google_id
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from users table
    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
