"""add_rag_system_tables

Revision ID: f3eebf86345c
Revises: 97b376b85238
Create Date: 2025-08-15 01:07:04.449441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3eebf86345c'
down_revision: Union[str, Sequence[str], None] = '97b376b85238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'email'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
